CREATE TABLE `tb_clientes` (
  `CLIENTE_ID` int NOT NULL AUTO_INCREMENT,
  `CLIENTE_NOMECOMPLETO` varchar(40) NOT NULL,
  `CLIENTE_EMAIL` varchar(40) DEFAULT NULL,
  `CLIENTE_CELULAR` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`CLIENTE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
